[versions]
ksp = "2.2.0-2.0.2"
kotlin = "2.2.0"
kotest= "6.0.0.M5"
[libraries]
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-framework-symbol-processor = { module = "io.kotest:kotest-framework-symbol-processor-jvm", version.ref = "kotest" }
kotest-runner-junit = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }

[plugins]
kotest= {id="io.kotest", version.ref="kotest"}
ksp = {id = "com.google.devtools.ksp", version.ref="ksp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }